# Generated by Django 5.1.3 on 2026-06-17 16:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last_seen', models.DateTimeField(db_index=True)),
                ('last_path', models.CharField(blank=True, max_length=200)),
                ('active_ws', models.IntegerField(default=0)),
                ('session_id', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('date', models.DateField(db_index=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('source', models.CharField(choices=[('client', 'client'), ('server', 'server'), ('ws', 'ws'), ('system', 'system')], default='client', max_length=8)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('target', models.CharField(blank=True, max_length=200)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['date', 'event_type'], name='analytics_e_date_ed1956_idx'), models.Index(fields=['user', 'date'], name='analytics_e_user_id_afd456_idx'), models.Index(fields=['event_type', 'created_at'], name='analytics_e_event_t_ef40a5_idx')],
            },
        ),
    ]
