# Generated by Django 5.1.3 on 2025-12-08 16:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMesh',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for the mesh', max_length=255)),
                ('file', models.FileField(help_text='The actual mesh file (STL, DAE, OBJ)', upload_to='meshes/%Y/%m/%d/')),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(help_text='File extension (.stl, .dae, .obj)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_meshes', to='workspace.canvas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_meshes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Mesh',
                'verbose_name_plural': 'Custom Meshes',
                'ordering': ['-created_at'],
                'unique_together': {('canvas', 'name')},
            },
        ),
    ]
